In [33]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import numpy as np


In [50]:
tokenizer = AutoTokenizer.from_pretrained("ipuneetrathore/bert-base-cased-finetuned-finBERT")
model = AutoModelForSequenceClassification.from_pretrained("ipuneetrathore/bert-base-cased-finetuned-finBERT")

Downloading:   0%|          | 0.00/1.29k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/213k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/40.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/433M [00:00<?, ?B/s]

In [24]:
sys.path.extend('C:\\Users\\sloth\\Desktop\\stonks\\finBERT\\finbert\\')

In [29]:
inputs = tokenizer("Tesla stocks will go up next year.", return_tensors="pt")
labels = torch.tensor([1]).unsqueeze(0)  # Batch size 1
outputs = model(**inputs, labels=labels)



outputs[1]

tensor([[ 1.9150, -2.3791, -0.5665]], grad_fn=<AddmmBackward>)

In [10]:
labels

tensor([[1]])

In [27]:
from finBERT import *

ModuleNotFoundError: No module named 'finBERT'

In [67]:
text = "I am long on Tesla."

In [71]:
def get_sentiment(text):
    MAX_LEN = 160
    class_names = [-1, 0, 1]

    encoded_new = tokenizer.encode_plus(
                            text,                      # Sentence to encode.
                            add_special_tokens = True,        # Add '[CLS]' and '[SEP]'
                            max_length = MAX_LEN,             # Pad & truncate all sentences.
                            padding = True,
                            return_attention_mask = True,     # Construct attn. masks.
                            return_tensors = 'pt', 
                            truncation=True# Return pytorch tensors.
                       )

    # Add the encoded sentence to the list.    
    input_idst = (encoded_new['input_ids'])
    attention_maskst = (encoded_new['attention_mask'])

    # Convert the lists into tensors.
    input_idst = torch.cat([input_idst], dim=0)
    attention_maskst = torch.cat([attention_maskst], dim=0)


    new_test_output = model(input_idst, token_type_ids=None, 
                          attention_mask=attention_maskst)

    logits = new_test_output[0]
    predicted = logits.detach().numpy()

    # Store predictions
    flat_predictions = np.concatenate(predicted, axis=0)

    # For each sample, pick the label (0 or 1) with the higher score.
    new_predictions = np.argmax(flat_predictions).flatten()

    return class_names[new_predictions[0]]

In [36]:
new_predictions

array([0], dtype=int64)

tensor([[ 1.8764, -1.7723, -1.4017]], grad_fn=<AddmmBackward>)

In [43]:
text

'I am bullish on Tesla for the next quarter. I think it is likely that Apple stock will rally.'

In [57]:
torch.device()

TypeError: Device() received an invalid combination of arguments - got (), but expected one of:
 * (torch.device device)
 * (str type, int index)


In [58]:
torch.cuda.current_device()

0

In [59]:
torch.cuda.is_available() 

True

In [60]:
torch.cuda.get_device_name(0)

'GeForce RTX 2080 Ti'

In [69]:
text="If not, it's just $100....the only downer may be that the $100 came from selling off shares of STEV, and now it's climbing."

In [77]:
get_sentiment(text)

0

In [76]:
text = "Buying 500 more shares on Monday"

In [74]:
text

'Buying 500 more shares on Monday 💰'